### ISSUE TITLE
InvalidArgumentException with new Extender::removeCacheFiles method

### ISSUE THREAD

**Issue by alexej-d** [hechoendrupal/drupal-console-extend-plugin#11]
I am seeing this error since the last commit after running composer (install or update):
```
[InvalidArgumentException]
  The "/[MY CURRENT ROOT]/console/cache/" directory does not exist.
```

**Comment by jmolivas** [comment]
Fixed with https://github.com/hechoendrupal/drupal-console-extend-plugin/pull/12 a new [0.8.0](https://github.com/hechoendrupal/drupal-console-extend-plugin/releases/tag/0.8.0) release was tagged.
