### ISSUE TITLE
0.5.0 causes error during install

### ISSUE THREAD

**Issue by pwolanin** [hechoendrupal/drupal-console-extend-plugin#9]
Our CI builds that run composer install are failing when pulling in the 0.5.0 release

```
PHP Warning:  Uncaught ErrorException: require_once(ExtenderManager.php): failed to open stream: No such file or directory in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code:16
```

**Comment by pwolanin** [comment]
Looks to be duplicate to https://github.com/hechoendrupal/drupal-console-extend-plugin/pull/8

**Comment by jmolivas** [comment]
@pwolanin  PR #8 and new release tagged https://github.com/hechoendrupal/drupal-console-extend-plugin/releases/tag/0.6.0

**Comment by pwolanin** [comment]
Thanks
